### ISSUE TITLE
IGAMT generating invalid profile

### ISSUE THREAD

**Issue by carolinerosin** [usnistgov/igamt#31]
when using profile components, IGAMT is generating an invalid XML profile. It is impossible to export to GVT.
The problem is that some segment are defined multiple time and that violated the schema for the profile.

See OBX_ELR_ARLN-1 for example in the Profile.xml

[Main-IG-APHL-08052019-5d48492984aecbc03a5cf2e0_20190805_143731.zip](https://github.com/usnistgov/igamt/files/3522859/Main-IG-APHL-08052019-5d48492984aecbc03a5cf2e0_20190805_143731.zip)

**Comment by carolinerosin** [comment]
The workaround for that one is to export composite profiles one by one in GVT. Would be nice to be fixed, but not urgent.

**Comment by Jungyubw** [comment]
@carolinerosin 
This issue is come from buidling Composite Prfile.
The tool is generating same name of Segment for Segment Level Composite profile, becasue you are using same extension (ARLN) for three composite profile.

I am not sure what we decided before, but If you use different exrension for each composite profile, it will be okay. (In this case we need to guide extension should be unique.)

Or I can add arbitary random number for segment name when the tool generates segment. Do you want it?

Thanks.

**Comment by carolinerosin** [comment]
Let's talk to Rob about that to see what he prefers
